name: Java CI with Gradle

on:
#   push:
#     branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  

permissions:
  contents: read
env:
  DATREE_TOKEN: ${{ secrets.DATREE_TOKEN }} 


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Add execute permission to Gradle
      run: chmod +x gradlew
    - name: Build with Gradle 
      uses:  gradle/gradle-build-action@v2.3.3
      with:
        arguments: build
    # Triggering SonarQube analysis as results of it are required by Quality Gate check.
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
    # Check the Quality Gate status.
    - name: SonarQube Quality Gate check
      id: sonarqube-quality-gate-check
      uses: sonarsource/sonarqube-quality-gate-action@master
      # Force to fail step after specific time.
      timeout-minutes: 5
      env:
       SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 
       
    - name: Run Datree Policy Check
      uses: datreeio/action-datree@main
      with:
        path: '**/*.yaml'
        cliArguments: '--only-k8s-files'
