name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
 

permissions:
  contents: read
env:
  DATREE_TOKEN: ${{ secrets.DATREE_TOKEN }} 


jobs:
  build:

    runs-on: self-hosted

    steps:
    #JDK WITH GRADLE
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Add execute permission to Gradle
      run: chmod +x gradlew
    - name: Build with Gradle 
      uses:  gradle/gradle-build-action@v2.3.3
      with:
        arguments: build
        
        
    # SONARQUBE    
    # Triggering SonarQube analysis as results of it are required by Quality Gate check.
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
    # Check the Quality Gate status.
    - name: SonarQube Quality Gate check
      id: sonarqube-quality-gate-check
      uses: sonarsource/sonarqube-quality-gate-action@master
      # Force to fail step after specific time.
      timeout-minutes: 5
      env:
       SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 
       
       
     #DATREE
    - name: Run Datree Policy Check
      uses: datreeio/action-datree@main
      with:
        path: 'kube.yaml'
        cliArguments: '--only-k8s-files'
    
    
    #DOCKER
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: bopgeek/firstgithubactionapp:latest
